dist: trusty
sudo: false

language: node_js
node_js:
  - "10.16.0"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - npm install
  - npm i -g @angular/cli

script:
  # Use Chromium instead of Chrome.
  - cd ./client
  - npm i
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run e2e -- --watch=false --protractor-config=protractor-ci.conf.js